apiVersion: v1
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:${IMAGE_TAG}'
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        binary: {}
        type: Binary
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'nginx:1.16-el8'
            namespace: openshift
        type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - github:
            secret: MCtm4rjz1pnjAMqlRwtq
          type: GitHub
        - generic:
            secret: ELhKIb5HGO8kfq7Zohn6
          type: Generic
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      generation: 4
      labels:
        build: ${NAME}
      managedFields:
        - apiVersion: build.openshift.io/v1
          fieldsType: FieldsV1
          fieldsV1:
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:build': {}
            'f:spec':
              'f:output':
                'f:to':
                  .: {}
                  'f:kind': {}
                  'f:name': {}
              'f:runPolicy': {}
              'f:source':
                'f:binary': {}
                'f:type': {}
              'f:strategy':
                'f:sourceStrategy':
                  .: {}
                  'f:from':
                    .: {}
                    'f:kind': {}
                    'f:name': {}
                    'f:namespace': {}
                'f:type': {}
              'f:triggers': {}
          manager: oc
          operation: Update
          time: '2021-10-04T20:48:41Z'
        - apiVersion: build.openshift.io/v1
          fieldsType: FieldsV1
          fieldsV1:
            'f:status':
              'f:lastVersion': {}
          manager: openshift-apiserver
          operation: Update
          time: '2021-10-04T21:39:46Z'
      name: ${NAME}
      namespace: ${NAMESPACE}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      generation: 1
      labels:
        build: ${NAME}
      managedFields:
        - apiVersion: image.openshift.io/v1
          fieldsType: FieldsV1
          fieldsV1:
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:build': {}
          manager: oc
          operation: Update
          time: '2021-10-04T20:48:41Z'
      name: ${NAME}
kind: Template
parameters:
- name: NAMESPACE
  required: true
  description: The namespace in which to deploy
- name: NAME
  required: true
  description: The name of the components
- name: IMAGE_TAG
  required: true
  description: The output image stream tag