apiVersion: v1
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:${IMAGE_TAG}'
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        binary: {}
        type: Binary
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'nginx:1.16-el8'
            namespace: openshift
        type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - github:
            secret: MCtm4rjz1pnjAMqlRwtq
          type: GitHub
        - generic:
            secret: ELhKIb5HGO8kfq7Zohn6
          type: Generic
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      generation: 4
      labels:
        build: ${NAME}
      name: ${NAME}
      namespace: ${TOOLS_NAMESPACE}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      generation: 1
      labels:
        build: ${NAME}
      name: ${NAME}
kind: Template
parameters:
- name: TOOLS_NAMESPACE
  required: true
  description: The tools namespace (where the images are built)
- name: NAME
  required: true
  description: The name of the components
- name: IMAGE_TAG
  required: true
  description: The output image stream tag